FROM golang:1.19.0-buster as build

WORKDIR /usr/src/app

COPY go.mod go.sum ./

RUN go mod download && go mod verify

COPY . .

RUN go build -ldflags="-w -s" -v -o /usr/local/bin/godemo 

FROM rockylinux:8

COPY --from=build /usr/local/bin/godemo /usr/local/bin/godemo

CMD ["/usr/local/bin/godemo"]

