# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:

  debug:
    cmds:
      - ./main

  build:
    deps:
      - apidocs
    cmds:
      - go build -ldflags="-w -s" main.go
    vars:
      GIT_COMMIT:
        sh: git log -n 1 --format=%h

  apidocs:
    cmds:
      - swag init .