name: Pull Request Build

on:
  pull_request:
    branches:
      - master

jobs:

  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go 1.18
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Upgrade upx
      run: |
        # try to fix https://github.com/jenkins-zh/jenkins-cli/issues/493
        wget https://github.com/upx/upx/releases/download/v3.96/upx-3.96-amd64_linux.tar.xz
        tar xvf upx-3.96-amd64_linux.tar.xz
        upx-3.96-amd64_linux/upx -V
        sudo mv upx-3.96-amd64_linux/upx $(which upx)
        upx -V
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v3.2.0
      with:
        version: latest
        args: release --skip-publish --rm-dist

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@0.2.1
      if: github.event_name == 'pull_request'
      with:
        scan-type: 'fs'
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'

  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Go 1.18
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3.0.0
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
          version: v1.45.2
      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v2
        with:
          golangci_lint_flags: "--disable-all -E golint"
          level: warning # GitHub Status Check won't become failure with this level.
  security:
    runs-on: ubuntu-20.04
    env:
      GO111MODULE: on
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3.0.0

      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        with:
          args: '-exclude=G402,G204,G304,G110,G306,G107 ./...'